export enum SpecializationSlug {
  Blood = 'blood',
  Frost = 'frost',
  Unholy = 'unholy',
  Havoc = 'havoc',
  Vengeance = 'vengeance',
  Balance = 'balance',
  Feral = 'feral',
  Guardian = 'guardian',
  Restoration = 'restoration',
  Devastation = 'devastation',
  Preservation = 'preservation',
  BeastMastery = 'beast-mastery',
  Marksmanship = 'marksmanship',
  Survival = 'survival',
  Arcane = 'arcane',
  Fire = 'fire',
  Brewmaster = 'brewmaster',
  Windwalker = 'windwalker',
  Mistweaver = 'mistweaver',
  Holy = 'holy',
  Protection = 'protection',
  Retribution = 'retribution',
  Discipline = 'discipline',
  Shadow = 'shadow',
  Assassination = 'assassination',
  Outlaw = 'outlaw',
  Subtlety = 'subtlety',
  Elemental = 'elemental',
  Enhancement = 'enhancement',
  Affliction = 'affliction',
  Demonology = 'demonology',
  Destruction = 'destruction',
  Arms = 'arms',
  Fury = 'fury',
}

export default SpecializationSlug;
